name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Verify
    uses: yagee-de/gh-workflows/.github/workflows/maven-verify.yml@main
    with:
      matrix-exclude: >
        [
          {"jdk": "8"}
        ]
