name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Verify
    uses: yagee-de/gh-workflows/.github/workflows/maven-verify.yml@main
    with:
      ff-site-goal: ''
      ff-goal: '-P run-its verify'
      failure-upload-path: |
          ./**/surefire-reports
          ./**/failsafe-reports
          ./**/screenshots
          ./**/*error*.log
          ./**/*test.log
      matrix-exclude: >
        [
          {"os": "macOS-latest"},
          {"jdk": "8"}
        ]
